server:
  port: 80
spring:
  application:
    name: amor-customer
  datasource:
    url: jdbc:mysql://49.234.76.112:3306/amor?useSSL=false&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1218
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

#redis配置
  redis:
    host: 127.0.0.1
    password: 1218
    port: 6379
    database: 6
  thymeleaf:
    #开发时关闭缓存，不然没发看到实时页面
    cache: false
    #spring.thymeleaf.mode的默认值是HTML5，其实是一个很严格的检查，改为LEGACYHTML5可以得到一个可能更友好亲切的格式要求。
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html


mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml # mapper.xml 包路径
  type-aliases-package: dxt.wj.customer.modelpo.po #别名
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #日志工具

