server:
  port: 8001
spring:
  application:
    name: amor-customer
  datasource:
    url: jdbc:mysql://49.234.76.112:3306/amor?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1218
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: