server:
  port: 8001 #端口

#spring:
#  devtools:   spring热部署
#    restart:
  #      enabled: false

#spring
spring:
  application:
    name: amor-customer #模块名
  datasource: #数据连接
    url: jdbc:mysql://49.234.76.112:3306/amor?useSSL=false&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1218

mybatis:
  mapper-locations: classpath*:mapper/**.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
